name: tests
on:
  push:
jobs:
  tests:
    name: Run all tests locally on Ubuntu
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Print commit id and message
        run: |
          git show -s --format='%h %s'
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Build prod app
        run: npm run build